export const LOAD_SKILLS = 'LOAD_SKILLS';
export const LOAD_SKILLS_SUCCESS = 'LOAD_SKILLS_SUCCESS';
export const LOAD_SKILLS_ERROR = 'LOAD_SKILLS_ERROR';
export const CLEAR_SKILLS = 'CLEAR_SKILLS';
export const FILTER_SKILLS = 'FILTER_SKILLS';
export const SEARCH_SKILLS = 'SEARCH_SKILLS';
export const PASS_SEARCH_SKILLS = 'PASS_SEARCH_SKILLS';
export const SORT_SKILLS = 'SORT_SKILLS';
export const PAGE_SKILLS = 'PAGE_SKILLS';

export const APPEND_ENTITIES = 'APPEND_ENTITIES';
export const CLEAR_ENTITIES = 'CLEAR_ENTITIES';
